// Home page components barrel export
export { HeroSection } from './HeroSection';
export { TestSection } from './TestSection';
export { AthletesSection } from './AthletesSection';
export { PricesAllMovementsSection } from './PricesAllMovementsSection';
export { OrganizationEquipmentSection } from './OrganizationEquipmentSection';
export { WeightCategoriesSection } from './WeightCategoriesSection';
export { SchedulesSection } from './SchedulesSection';
export { LocalizacionSection } from './LocalizacionSection';
export { RulesSection } from './RulesSection';
export { HowToEnterSection } from './HowToEnterSection';
export { WinnersSection } from './WinnersSection';
export { Footer } from './Footer';
