export {
  FER_COLORS,
  FER_EVENT,
  PARTICLE_COUNT,
  CONFETTI_COUNT,
  CANVAS_PARTICLE_COUNT,
  CANVAS_CONFETTI_COUNT,
  FER_VIDEO_CONFIG,
  HERO_SLIDESHOW_IMAGES,
  HERO_BRAND_ICONS,
  HERO_CAMISETA_BG,
  EXPERIENCE_LEVELS,
  EXPERIENCE_DESCRIPTIONS,
  EXPERIENCE_LABELS,
  MODALIDAD_VALUES,
  MODALIDAD_LABELS,
  MODALIDAD_DESCRIPTIONS,
  MODALIDAD_LIFTS,
  SECTION_IDS,
  SCROLL_OFFSET,
  POLAROID_PHOTOS,
  POLAROID_START_OFFSET_X,
  POLAROID_START_ROTATION,
  NAV_LINKS,
} from './constants';

export type { Experiencia, Modalidad } from './constants';

export { CLUB_PHOTOS } from './clubPhotos';
export {
  FER_CUP_LOGO_IMAGE,
  FER_QUE_ES_IMAGE,
  FER_QUE_INCLUYE_JUECES_IMAGE,
  FER_QUE_INCLUYE_SPOTTERS_IMAGE,
  FER_QUIEN_PUEDE_SIN_ENTRENADOR_IMAGE,
  FER_QUIEN_PUEDE_SIN_EXPERIENCIA_IMAGE,
  FER_POLAROID_0_IMAGE,
  FER_UBICACION_INSTALACIONES_IMAGES,
  FER_SOBRE_HERO_IMAGE,
  FER_SOBRE_MISSION_IMAGE,
  FER_SOBRE_TEAM_GRS_IMAGE,
  FER_SOBRE_TEAM_JUDGES_IMAGE,
  FER_SOBRE_TEAM_COMMUNITY_IMAGE,
} from './mediaCdnUrls';
