// <auto-generated />
using System;
using GrCup.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrCup.Api.Migrations
{
    [DbContext(typeof(GrCupDbContext))]
    [Migration("20260710160318_AddInscripcionEstado")]
    partial class AddInscripcionEstado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GrCup.Api.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckinAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Club")
                        .HasColumnType("longtext");

                    b.Property<string>("Coach")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("QrCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WeightCategory")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Sex");

                    b.HasIndex("Status");

                    b.HasIndex("WeightCategory");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("GrCup.Api.Models.CodigoReferido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CodigoNormalizado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.HasIndex("InscripcionId");

                    b.ToTable("CodigosReferido");
                });

            modelBuilder.Entity("GrCup.Api.Models.Competicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EventoConfig")
                        .HasColumnType("json");

                    b.Property<string>("FaviconUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HorariosReady")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LandingConfig")
                        .HasColumnType("json");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ModulesConfig")
                        .HasColumnType("json");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("QrSecret")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("ReferidosActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Tipo");

                    b.ToTable("Competiciones");
                });

            modelBuilder.Entity("GrCup.Api.Models.CuponDescuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CodigoNormalizado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LimiteUsos")
                        .HasColumnType("int");

                    b.Property<bool>("TieneFechaExpiracion")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TieneLimiteUsos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("CompeticionId", "CodigoNormalizado")
                        .IsUnique();

                    b.ToTable("CuponesDescuento");
                });

            modelBuilder.Entity("GrCup.Api.Models.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<int?>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<string>("WinnerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WinnerInstagram")
                        .HasColumnType("longtext");

                    b.Property<string>("WinnerName")
                        .HasColumnType("longtext");

                    b.Property<int?>("WinnerTicketCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Draws");
                });

            modelBuilder.Entity("GrCup.Api.Models.EmailConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GmailAppPassword")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MainProvider")
                        .HasColumnType("int");

                    b.Property<string>("SmtpEmailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SmtpPassword")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.ToTable("EmailConfig");
                });

            modelBuilder.Entity("GrCup.Api.Models.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceptaTerminos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Apellido1")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CategoriaPeso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CheckinAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CodigoCupon")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CuponDescuentoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("EmailEnviadoAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailEnviadoError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EmailEnviadoStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Experiencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ImporteDescuento")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<bool>("PagoConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ParticipacionConfirmada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("QrCode")
                        .HasColumnType("longtext");

                    b.Property<string>("QrImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("QuiereHandler")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("QuierePeakProgram")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ReferralCodeId")
                        .HasColumnType("int");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("SubtotalAntesDescuento")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TieneEntrenador")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoDescuentoCupon")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("ValorDescuentoCupon")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CuponDescuentoId");

                    b.HasIndex("Email");

                    b.HasIndex("Modalidad");

                    b.HasIndex("PagoConfirmado");

                    b.HasIndex("StripeSessionId");

                    b.HasIndex("CompeticionId", "Email");

                    b.ToTable("Inscripciones");
                });

            modelBuilder.Entity("GrCup.Api.Models.InscripcionConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("InscripcionConfig");
                });

            modelBuilder.Entity("GrCup.Api.Models.InscripcionEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("InscripcionesAbiertas")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId")
                        .IsUnique();

                    b.ToTable("inscripcion_estado", (string)null);
                });

            modelBuilder.Entity("GrCup.Api.Models.InscripcionPreparada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Preparadas")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("InscripcionesPreparadas");
                });

            modelBuilder.Entity("GrCup.Api.Models.LiftEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LiftType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("AthleteId", "LiftType", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("LiftEntries");
                });

            modelBuilder.Entity("GrCup.Api.Models.LiftEntryInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<bool?>("Juez1Voto")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Juez2Voto")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("Juez3Voto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LiftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("InscripcionId", "LiftType", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("LiftEntriesInscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewUserReferral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoReferidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ImporteAcumuladoReferente")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ImporteDescuento")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StripeRefundId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoDescuento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("VecesUsado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReferidoId");

                    b.HasIndex("InscripcionId");

                    b.ToTable("NewUserReferrals");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewsletterEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.HasIndex("CompeticionId", "Status");

                    b.ToTable("NewsletterEmails");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewsletterEmailMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CdnUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("NewsletterEmailId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NewsletterEmailId");

                    b.ToTable("NewsletterEmailMedia");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewsletterSendProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchSize")
                        .HasColumnType("int");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("NewsletterEmailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextBatchAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PendingRecipients")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("SentCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("TotalRecipients")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.HasIndex("NewsletterEmailId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("NewsletterSendProgress");
                });

            modelBuilder.Entity("GrCup.Api.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("StripeSessionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TicketCount")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("StripeSessionId");

                    b.HasIndex("Email", "PaymentMethod", "IsPaid");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("GrCup.Api.Models.RaffleConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisabledMessage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RaffleMethod")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("raffle_config_legacy", (string)null);
                });

            modelBuilder.Entity("GrCup.Api.Models.RaffleProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DisplayOrder");

                    b.HasIndex("IsActive");

                    b.ToTable("RaffleProducts");
                });

            modelBuilder.Entity("GrCup.Api.Models.ReferidoConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LimiteUsos")
                        .HasColumnType("int");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ModoAcumulativo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("MultiplicadorAcumulativo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("TieneLimiteUsos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoDescuentoNuevoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDescuentoReferente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorDescuentoNuevoUsuario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorDescuentoReferente")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.ToTable("ReferidosConfig");
                });

            modelBuilder.Entity("GrCup.Api.Models.ReferidoUserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CodigoReferidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LimiteUsos")
                        .HasColumnType("int");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ModoAcumulativo")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("MultiplicadorAcumulativo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("TieneLimiteUsos")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TipoDescuentoNuevoUsuario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDescuentoReferente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorDescuentoNuevoUsuario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorDescuentoReferente")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReferidoId")
                        .IsUnique();

                    b.ToTable("ReferidosUserSetting");
                });

            modelBuilder.Entity("GrCup.Api.Models.ResponsableInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Value")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("ResponsableInscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.RifaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescripcionPremio")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaSorteo")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("GanadorConfirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("GanadorInscripcionId")
                        .HasColumnType("int");

                    b.Property<string>("NombrePremio")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NumeroGanador")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("PrecioTicket")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TicketsTotal")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId")
                        .IsUnique();

                    b.ToTable("RifaConfigs");
                });

            modelBuilder.Entity("GrCup.Api.Models.RifaTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BuyerNombre")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StripePaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Confirmado");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("CompeticionId", "NumeroTicket")
                        .IsUnique();

                    b.ToTable("RifaTickets");
                });

            modelBuilder.Entity("GrCup.Api.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("SexCategory")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WeightCategory")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.HasIndex("Date");

                    b.HasIndex("SexCategory", "WeightCategory");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("GrCup.Api.Models.SchedulePublishedConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Value")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.ToTable("SchedulePublishedConfig");
                });

            modelBuilder.Entity("GrCup.Api.Models.SorteoInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSorteo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FiltroAplicado")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int?>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroGanador")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("CompeticionId", "FechaSorteo");

                    b.ToTable("SorteosInscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.StripeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PublishableKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SecretKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.ToTable("StripeConfig");
                });

            modelBuilder.Entity("GrCup.Api.Models.TutorialInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Contenido")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("VideoId", "Tipo");

                    b.ToTable("TutorialInteractions");
                });

            modelBuilder.Entity("GrCup.Api.Models.UrlInscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UrlInscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSuperadmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsRoot");

                    b.HasIndex("IsSuperadmin");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GrCup.Api.Models.UsuarioCompeticion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("InvitationAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("InvitedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvitedByEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompeticionId");

                    b.HasIndex("UsuarioId", "CompeticionId")
                        .IsUnique();

                    b.ToTable("UsuariosCompeticiones");
                });

            modelBuilder.Entity("GrCup.Api.Models.UsuarioPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompeticionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Granted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "PermissionKey", "CompeticionId")
                        .IsUnique();

                    b.ToTable("UsuariosPermissions");
                });

            modelBuilder.Entity("GrCup.Api.Models.CodigoReferido", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrCup.Api.Models.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.CuponDescuento", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany("CuponesDescuento")
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.Draw", b =>
                {
                    b.HasOne("GrCup.Api.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("GrCup.Api.Models.EmailConfig", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.Inscripcion", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrCup.Api.Models.CuponDescuento", "CuponDescuento")
                        .WithMany()
                        .HasForeignKey("CuponDescuentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competicion");

                    b.Navigation("CuponDescuento");
                });

            modelBuilder.Entity("GrCup.Api.Models.InscripcionEstado", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.LiftEntry", b =>
                {
                    b.HasOne("GrCup.Api.Models.Athlete", "Athlete")
                        .WithMany("LiftEntries")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("GrCup.Api.Models.LiftEntryInscripcion", b =>
                {
                    b.HasOne("GrCup.Api.Models.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewUserReferral", b =>
                {
                    b.HasOne("GrCup.Api.Models.CodigoReferido", "CodigoReferido")
                        .WithMany("NewUserReferrals")
                        .HasForeignKey("CodigoReferidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrCup.Api.Models.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodigoReferido");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewsletterEmail", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewsletterEmailMedia", b =>
                {
                    b.HasOne("GrCup.Api.Models.NewsletterEmail", "NewsletterEmail")
                        .WithMany("Media")
                        .HasForeignKey("NewsletterEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsletterEmail");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewsletterSendProgress", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrCup.Api.Models.NewsletterEmail", "NewsletterEmail")
                        .WithOne("SendProgress")
                        .HasForeignKey("GrCup.Api.Models.NewsletterSendProgress", "NewsletterEmailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");

                    b.Navigation("NewsletterEmail");
                });

            modelBuilder.Entity("GrCup.Api.Models.ReferidoConfig", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.ReferidoUserSetting", b =>
                {
                    b.HasOne("GrCup.Api.Models.CodigoReferido", "CodigoReferido")
                        .WithOne("UserSetting")
                        .HasForeignKey("GrCup.Api.Models.ReferidoUserSetting", "CodigoReferidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodigoReferido");
                });

            modelBuilder.Entity("GrCup.Api.Models.RifaConfig", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithOne("RifaConfig")
                        .HasForeignKey("GrCup.Api.Models.RifaConfig", "CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.RifaTicket", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany("RifaTickets")
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrCup.Api.Models.Inscripcion", "Inscripcion")
                        .WithMany("RifaTickets")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Competicion");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.Schedule", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.SchedulePublishedConfig", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.SorteoInscripcion", b =>
                {
                    b.HasOne("GrCup.Api.Models.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrCup.Api.Models.Inscripcion", "Inscripcion")
                        .WithMany()
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Athlete");

                    b.Navigation("Competicion");

                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("GrCup.Api.Models.StripeConfig", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany()
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Competicion");
                });

            modelBuilder.Entity("GrCup.Api.Models.UsuarioCompeticion", b =>
                {
                    b.HasOne("GrCup.Api.Models.Competicion", "Competicion")
                        .WithMany("UsuarioCompeticiones")
                        .HasForeignKey("CompeticionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GrCup.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioCompeticiones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competicion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GrCup.Api.Models.UsuarioPermission", b =>
                {
                    b.HasOne("GrCup.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPermissions")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GrCup.Api.Models.Athlete", b =>
                {
                    b.Navigation("LiftEntries");
                });

            modelBuilder.Entity("GrCup.Api.Models.CodigoReferido", b =>
                {
                    b.Navigation("NewUserReferrals");

                    b.Navigation("UserSetting");
                });

            modelBuilder.Entity("GrCup.Api.Models.Competicion", b =>
                {
                    b.Navigation("CuponesDescuento");

                    b.Navigation("Inscripciones");

                    b.Navigation("RifaConfig");

                    b.Navigation("RifaTickets");

                    b.Navigation("UsuarioCompeticiones");
                });

            modelBuilder.Entity("GrCup.Api.Models.Inscripcion", b =>
                {
                    b.Navigation("RifaTickets");
                });

            modelBuilder.Entity("GrCup.Api.Models.NewsletterEmail", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("SendProgress");
                });

            modelBuilder.Entity("GrCup.Api.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioCompeticiones");

                    b.Navigation("UsuarioPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
